const { SlashCommandBuilder, PermissionsBitField, ChannelType } = require('discord.js');
const { requirePermission } = require('../utils/permissions');
const { getGuild } = require('../database/repository');

module.exports = [
  { data:new SlashCommandBuilder().setName('setlog').setDescription('Set the moderation log channel').addChannelOption(o=>o.setName('channel').setDescription('Text channel').addChannelTypes(ChannelType.GuildText).setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await getGuild(i.guild.id);g.logChannelId=i.options.getChannel('channel',true).id;await g.save();return i.reply('📋 Log channel configured.');} },
  { data:new SlashCommandBuilder().setName('setwelcome').setDescription('Set welcome channel').addChannelOption(o=>o.setName('channel').setDescription('Text channel').addChannelTypes(ChannelType.GuildText).setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await getGuild(i.guild.id);g.welcomeChannelId=i.options.getChannel('channel',true).id;await g.save();return i.reply('👋 Welcome channel configured.');} },
  { data:new SlashCommandBuilder().setName('setgoodbye').setDescription('Set goodbye channel').addChannelOption(o=>o.setName('channel').setDescription('Text channel').addChannelTypes(ChannelType.GuildText).setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await getGuild(i.guild.id);g.goodbyeChannelId=i.options.getChannel('channel',true).id;await g.save();return i.reply('👋 Goodbye channel configured.');} },
  { data:new SlashCommandBuilder().setName('autorole').setDescription('Set the automatic member role').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await getGuild(i.guild.id);g.autoRoleId=i.options.getRole('role',true).id;await g.save();return i.reply('🎭 Auto-role configured.');} },
  { data:new SlashCommandBuilder().setName('automod').setDescription('Enable or disable AutoMod').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled').setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await getGuild(i.guild.id);g.automod=i.options.getBoolean('enabled',true);await g.save();return i.reply(`🛡️ AutoMod ${g.automod?'enabled':'disabled'}.`);} },
  { data:new SlashCommandBuilder().setName('antilink').setDescription('Enable or disable link protection').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled').setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await getGuild(i.guild.id);g.antiLink=i.options.getBoolean('enabled',true);await g.save();return i.reply(`🔗 Anti-link ${g.antiLink?'enabled':'disabled'}.`);} },
  { data:new SlashCommandBuilder().setName('anticaps').setDescription('Enable or disable caps protection').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled').setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await getGuild(i.guild.id);g.antiCaps=i.options.getBoolean('enabled',true);await g.save();return i.reply(`🔠 Anti-caps ${g.antiCaps?'enabled':'disabled'}.`);} },
  { data:new SlashCommandBuilder().setName('antiraid').setDescription('Enable or disable raid detection').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled').setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await getGuild(i.guild.id);g.antiRaid=i.options.getBoolean('enabled',true);await g.save();return i.reply(`🚨 Anti-raid ${g.antiRaid?'enabled':'disabled'}.`);} },
  { data:new SlashCommandBuilder().setName('antinuke').setDescription('Enable or disable anti-nuke alerts').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled').setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.Administrator,'Administrator'))return;const g=await getGuild(i.guild.id);g.antiNuke=i.options.getBoolean('enabled',true);await g.save();return i.reply(`🛡️ Anti-nuke ${g.antiNuke?'enabled':'disabled'}.`);} },
];
