const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { getUser, db, save } = require('../utils/database');

module.exports = [
  { data:new SlashCommandBuilder().setName('balance').setDescription('Check your wallet and bank'), async execute(i){ const u=getUser(i.user.id); return i.reply(`💰 Wallet: **${u.cash}**\n🏦 Bank: **${u.bank}**\n💎 Total: **${u.cash+u.bank}**`); } },
  { data:new SlashCommandBuilder().setName('daily').setDescription('Claim daily coins'), async execute(i){ const u=getUser(i.user.id), now=Date.now(), day=86400000; if(now-u.daily<day)return i.reply({content:`⏳ Come back in ${Math.ceil((day-(now-u.daily))/3600000)} hour(s).`,ephemeral:true}); const amount=500; u.cash+=amount; u.daily=now; save(); return i.reply(`🎁 You received **${amount}** coins!`); } },
  { data:new SlashCommandBuilder().setName('work').setDescription('Work for coins'), async execute(i){ const u=getUser(i.user.id), now=Date.now(), cd=300000; if(now-u.work<cd)return i.reply({content:`⏳ You can work again in ${Math.ceil((cd-(now-u.work))/60000)} minute(s).`,ephemeral:true}); const amount=Math.floor(Math.random()*251)+150; u.cash+=amount; u.work=now; save(); return i.reply(`💼 You earned **${amount}** coins!`); } },
  { data:new SlashCommandBuilder().setName('deposit').setDescription('Deposit coins').addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true).setMinValue(1)), async execute(i){ const u=getUser(i.user.id), n=i.options.getInteger('amount',true); if(u.cash<n)return i.reply({content:'❌ Not enough cash.',ephemeral:true}); u.cash-=n; u.bank+=n; save(); return i.reply(`🏦 Deposited **${n}** coins.`); } },
  { data:new SlashCommandBuilder().setName('withdraw').setDescription('Withdraw coins').addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true).setMinValue(1)), async execute(i){ const u=getUser(i.user.id), n=i.options.getInteger('amount',true); if(u.bank<n)return i.reply({content:'❌ Not enough bank balance.',ephemeral:true}); u.bank-=n; u.cash+=n; save(); return i.reply(`💵 Withdrew **${n}** coins.`); } },
  { data:new SlashCommandBuilder().setName('pay').setDescription('Pay another user').addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)).addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true).setMinValue(1)), async execute(i){ const target=i.options.getUser('user',true), n=i.options.getInteger('amount',true); if(target.bot||target.id===i.user.id)return i.reply({content:'❌ Invalid payment target.',ephemeral:true}); const me=getUser(i.user.id), them=getUser(target.id); if(me.cash<n)return i.reply({content:'❌ Not enough cash.',ephemeral:true}); me.cash-=n; them.cash+=n; save(); return i.reply(`💸 Paid **${n}** coins to ${target}.`); } },
  { data:new SlashCommandBuilder().setName('leaderboard').setDescription('Show richest users'), async execute(i){ const rows=Object.entries(db.users).map(([id,u])=>({id,total:u.cash+u.bank})).sort((a,b)=>b.total-a.total).slice(0,10); if(!rows.length)return i.reply('No economy data yet.'); const desc=rows.map((r,n)=>`**${n+1}.** <@${r.id}> — **${r.total}** coins`).join('\n'); return i.reply({embeds:[new EmbedBuilder().setTitle('💰 Economy Leaderboard').setDescription(desc)]}); } },
];
