const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { getUser, User } = require('../database/repository');

const cooldown = (date, ms) => date && Date.now() - date.getTime() < ms;
const remaining = (date, ms, unit) => Math.ceil((ms - (Date.now() - date.getTime())) / unit);

module.exports = [
  { data:new SlashCommandBuilder().setName('balance').setDescription('Check your wallet and bank'), async execute(i){ const u=await getUser(i.user.id); return i.reply(`💰 Wallet: **${u.cash}**\n🏦 Bank: **${u.bank}**\n💎 Total: **${u.cash+u.bank}**`); } },
  { data:new SlashCommandBuilder().setName('daily').setDescription('Claim daily coins'), async execute(i){ const u=await getUser(i.user.id),ms=86400000;if(cooldown(u.lastDaily,ms))return i.reply({content:`⏳ Come back in ${remaining(u.lastDaily,ms,3600000)} hour(s).`,ephemeral:true});u.cash+=500;u.lastDaily=new Date();await u.save();return i.reply('🎁 You received **500** coins!'); } },
  { data:new SlashCommandBuilder().setName('weekly').setDescription('Claim weekly coins'), async execute(i){ const u=await getUser(i.user.id),ms=604800000;if(cooldown(u.lastWeekly,ms))return i.reply({content:`⏳ Come back in ${remaining(u.lastWeekly,ms,86400000)} day(s).`,ephemeral:true});u.cash+=2500;u.lastWeekly=new Date();await u.save();return i.reply('🎁 You received **2,500** coins!'); } },
  { data:new SlashCommandBuilder().setName('work').setDescription('Work for coins'), async execute(i){ const u=await getUser(i.user.id),ms=300000;if(cooldown(u.lastWork,ms))return i.reply({content:`⏳ Work again in ${remaining(u.lastWork,ms,60000)} minute(s).`,ephemeral:true});const amount=Math.floor(Math.random()*251)+150;u.cash+=amount;u.lastWork=new Date();await u.save();return i.reply(`💼 You earned **${amount}** coins!`); } },
  { data:new SlashCommandBuilder().setName('beg').setDescription('Beg for coins'), async execute(i){const u=await getUser(i.user.id),amount=Math.floor(Math.random()*101);u.cash+=amount;await u.save();return i.reply(amount?`🥺 Someone gave you **${amount}** coins.`:'🥺 Nobody gave you anything.');} },
  { data:new SlashCommandBuilder().setName('deposit').setDescription('Deposit coins').addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true).setMinValue(1)), async execute(i){const u=await getUser(i.user.id),n=i.options.getInteger('amount',true);if(u.cash<n)return i.reply({content:'❌ Not enough cash.',ephemeral:true});u.cash-=n;u.bank+=n;await u.save();return i.reply(`🏦 Deposited **${n}** coins.`);} },
  { data:new SlashCommandBuilder().setName('withdraw').setDescription('Withdraw coins').addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true).setMinValue(1)), async execute(i){const u=await getUser(i.user.id),n=i.options.getInteger('amount',true);if(u.bank<n)return i.reply({content:'❌ Not enough bank balance.',ephemeral:true});u.bank-=n;u.cash+=n;await u.save();return i.reply(`💵 Withdrew **${n}** coins.`);} },
  { data:new SlashCommandBuilder().setName('pay').setDescription('Pay another user').addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)).addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true).setMinValue(1)), async execute(i){const target=i.options.getUser('user',true),n=i.options.getInteger('amount',true);if(target.bot||target.id===i.user.id)return i.reply({content:'❌ Invalid payment target.',ephemeral:true});const me=await getUser(i.user.id),them=await getUser(target.id);if(me.cash<n)return i.reply({content:'❌ Not enough cash.',ephemeral:true});me.cash-=n;them.cash+=n;await Promise.all([me.save(),them.save()]);return i.reply(`💸 Paid **${n}** coins to ${target}.`);} },
  { data:new SlashCommandBuilder().setName('leaderboard').setDescription('Show richest users'), async execute(i){const rows=await User.find({}).sort({cash:-1,bank:-1}).limit(10);if(!rows.length)return i.reply('No economy data yet.');const desc=rows.map((u,n)=>`**${n+1}.** <@${u.userId}> — **${u.cash+u.bank}** coins`).join('\n');return i.reply({embeds:[new EmbedBuilder().setTitle('💰 Economy Leaderboard').setDescription(desc)]});} },
];
