const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { Giveaway } = require('../database/repository');
const { requirePermission } = require('../utils/permissions');
const { PermissionsBitField } = require('discord.js');

module.exports = [
  { data:new SlashCommandBuilder().setName('giveaway').setDescription('Manage giveaways').addSubcommand(s=>s.setName('start').setDescription('Start a giveaway').addIntegerOption(o=>o.setName('seconds').setDescription('Duration').setRequired(true).setMinValue(10).setMaxValue(604800)).addStringOption(o=>o.setName('prize').setDescription('Prize').setRequired(true)).addIntegerOption(o=>o.setName('winners').setDescription('Number of winners').setMinValue(1).setMaxValue(20))), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const seconds=i.options.getInteger('seconds',true),prize=i.options.getString('prize',true),winners=i.options.getInteger('winners')||1,ends=Date.now()+seconds*1000;const msg=await i.channel.send({embeds:[new EmbedBuilder().setTitle('🎉 Giveaway!').setDescription(`Prize: **${prize}**\nReact with 🎉 to enter!\nWinners: **${winners}**\nEnds: <t:${Math.floor(ends/1000)}:R>`)]});await msg.react('🎉');const giveaway=await Giveaway.create({guildId:i.guild.id,channelId:i.channel.id,messageId:msg.id,prize,winners,endsAt:new Date(ends)});setTimeout(()=>finish(giveaway.id).catch(console.error),seconds*1000);return i.reply({content:'✅ Giveaway started.',ephemeral:true});} },
  { data:new SlashCommandBuilder().setName('giveaway-end').setDescription('End a giveaway').addStringOption(o=>o.setName('message_id').setDescription('Giveaway message ID').setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await Giveaway.findOne({messageId:i.options.getString('message_id',true),guildId:i.guild.id});if(!g)return i.reply({content:'❌ Giveaway not found.',ephemeral:true});await finish(g.id);return i.reply('🏁 Giveaway ended.');} },
  { data:new SlashCommandBuilder().setName('giveaway-reroll').setDescription('Reroll a giveaway').addStringOption(o=>o.setName('message_id').setDescription('Giveaway message ID').setRequired(true)), async execute(i){if(!await requirePermission(i,PermissionsBitField.Flags.ManageGuild,'Manage Server'))return;const g=await Giveaway.findOne({messageId:i.options.getString('message_id',true),guildId:i.guild.id});if(!g)return i.reply({content:'❌ Giveaway not found.',ephemeral:true});const channel=i.guild.channels.cache.get(g.channelId),msg=channel&&await channel.messages.fetch(g.messageId).catch(()=>null);const users=msg?await msg.reactions.cache.get('🎉')?.users.fetch():null;const eligible=users?users.filter(u=>!u.bot).map(u=>u):[];if(!eligible.length)return i.reply('❌ No eligible entrants.');const winner=eligible[Math.floor(Math.random()*eligible.length)];return i.reply(`🎉 New winner: ${winner}! Prize: **${g.prize}**`);} },
];

async function finish(id){const g=await Giveaway.findById(id);if(!g||g.ended)return;const channel=await global.__discordClient?.channels.fetch(g.channelId).catch(()=>null);const msg=channel&&await channel.messages.fetch(g.messageId).catch(()=>null);if(!msg){g.ended=true;await g.save();return;}const reaction=msg.reactions.cache.get('🎉');const users=reaction?await reaction.users.fetch():null;const eligible=users?users.filter(u=>!u.bot).map(u=>u):[];const winners=[];while(eligible.length&&winners.length<g.winners)winners.push(eligible.splice(Math.floor(Math.random()*eligible.length),1)[0]);g.ended=true;await g.save();await channel.send(winners.length?`🎉 Congratulations ${winners.join(', ')}! You won **${g.prize}**!`:`🎉 Giveaway ended with no eligible entrants.`);}
